title: ingenious-machines
description: >
  Tillmann Radmer's blog on machine learning, artificial intelligence, software development and more.
permalink: /blog/:year/:month/:day/:title

author:
  first_name: Tillmann
  last_name: Radmer
  email: tillmann.radmer@gmail.com
  github_username: radmerti
  linkedin_username: tillmannradmer
  twitter_username: till_tweets
  instagram_username: tillmannradmer

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"