description: >
  Tillmann Radmer's blog on AI, software development and more.
baseurl: /                      # the subpath of your site, e.g. /blog/
url: http://radmerti.github.io  # the base hostname & protocol for your site
name: Tillmann Radmer
email: tillmann.radmer@gmail.com
github_username: radmerti
linkedin_username: tillmannradmer
twitter_username: till_tweets
permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"